name: Deployment From Github To AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_TOKEN}}
         logout: true
      - name: Build Server image
        run: docker build -t alisleem811/bluepages-server .
      - name: Tag our Image
        run: docker tag alisleem811/bluepages-server 
          alisleem811/bluepages-server:latest
      - name: Push to dockerhub
        run: docker push alisleem811/bluepages-server
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: blue-pages-docker
          environment_name: Bluepagesdocker-env
          version_label: "blue-pages-docker-deployment-19-11_22:07"
          region: us-east-1

